version: '3.3'
services:
  event_db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: event
      POSTGRES_PASSWORD: CHANGE-ME
    volumes:
      - event_db_folder:/var/lib/postgresql/data
    networks:
      - event_network
  event_backend:
    build: ./event-service
    command: rails server -b 0.0.0.0
    environment:
      - RAILS_ENV=development
      - DATABASE_USER_NAME=event
      - DATABASE_PASSWORD=CHANGE-ME
      - DATABASE_HOST=event_db
    restart: always
    ports:
      - "3111:3000"
    networks:
      - event_network
    depends_on:
      - event_db
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
  front_end:
    build: ./front-end
    command: tail -f /dev/null
    restart: always
    networks: 
      - event_network
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
  nginx:
    image: nginx
    # command: tail -f /dev/null
    ports:
      - "8888:80"
    networks:
      - event_network
    volumes:
      - ./nginx:/etc/nginx
      - ./front-end/dist:/dist
    depends_on:
      - event_backend
networks:
  event_network:
volumes:
  event_db_folder:
    external:
      name: event_database
