version: '3.3'
services:
  event-db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: event
      POSTGRES_PASSWORD: CHANGE-ME
    volumes:
      - event_db_folder:/var/lib/postgresql/data
    networks:
      - event_network
  event-service:
    build: ./event-service
    command: rails server -b 0.0.0.0
    environment:
      - RAILS_ENV=development
      - DATABASE_USER_NAME=event
      - DATABASE_PASSWORD=CHANGE-ME
      - DATABASE_HOST=event-db
    restart: always
    networks:
      - event_network
    depends_on:
      - event-db
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached

  participation-db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHANGE-ME
    volumes:
      - participation_db_folder:/var/lib/postgresql/data
    networks:
      - event_network
  participation-service:
    build: ./participation-service
    command: rails server -b 0.0.0.0
    # command: tail -f /dev/null
    environment:
      - RAILS_ENV=development
      - DATABASE_USER_NAME=postgres
      - DATABASE_PASSWORD=CHANGE-ME
      - DATABASE_HOST=participation-db
    restart: always
    networks:
      - event_network
    depends_on:
      - participation-db
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached

  user-db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHANGE-ME
    volumes:
      - participation_db_folder:/var/lib/postgresql/data
    networks:
      - event_network
  user-service:
    build: ./user-service
    command: rails server -b 0.0.0.0
    # command: tail -f /dev/null
    environment:
      - RAILS_ENV=development
      - DATABASE_USER_NAME=postgres
      - DATABASE_PASSWORD=CHANGE-ME
      - DATABASE_HOST=user-db
    restart: always
    networks:
      - event_network
    depends_on:
      - user-db
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
  front_end:
    build: ./front-end
    command: tail -f /dev/null
    restart: always
    networks: 
      - event_network
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    profiles:
      - "frontend"
  nginx:
    image: nginx
    # command: tail -f /dev/null
    ports:
      - "4200:80"
    networks:
      - event_network
    volumes:
      - ./nginx:/etc/nginx
      - ./front-end/dist:/dist
    depends_on:
      - event-service
      - participation-service
networks:
  event_network:
volumes:
  event_db_folder:
    external:
      name: event_database
  participation_db_folder:
    external:
      name: participation_database