apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: organizer-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  # ingressClassName: traefik
  rules:
    -  http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik
                port:
                  number: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix
spec:
  stripPrefixRegex:
    regex:
      - /api/
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: user-auth
spec:
  forwardAuth:
    address: http://user-service:3000/users/authenticate
    authResponseHeaders:
      - X-User-Id
      - X-User-Name
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
spec:
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: front-end-service
          port: 80
    - kind: Rule
      match: PathPrefix(`/api/events`)
      middlewares:
        - name: strip-api-prefix
        # - name: user-auth
      services:
        - name: event-service
          port: 3000
    - kind: Rule
      match: PathPrefix(`/api/users`)
      middlewares:
        - name: strip-api-prefix
      services:
        - name: user-service
          port: 3000
    - kind: Rule
      match: PathPrefix(`/api/users/current`)
      middlewares:
        - name: strip-api-prefix
        - name: user-auth
      services:
        - name: user-service
          port: 3000      
    - kind: Rule
      match: PathPrefix(`/api/participations`)
      middlewares:
        - name: strip-api-prefix
      services:
        - name: participation-service
          port: 3000
