apiVersion: apps/v1
kind: Deployment
metadata:
  name: participation-deployment
  labels:
    app: participation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participation
  template:
    metadata:
      labels:
        app: participation
    spec:
      containers:
      - name: participation
        image: slaac/participation-service:0.2.3
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: participation-db-config
              key: postgres_host
        - name: DATABASE_USER_NAME
          valueFrom:
            configMapKeyRef:
              name: participation-db-config
              key: postgres_user      
        - name: DATABASE_PASSWORD 
          valueFrom:
            configMapKeyRef:
              name: participation-db-config
              key: postgres_password
        - name: WEB_HOST 
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: web_host               
---
apiVersion: v1
kind: Service
metadata:
  name: participation-service
spec:
  selector:
    app: participation
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000