apiVersion: v1
kind: PersistentVolume
metadata:
  name: participation-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: participation-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: participation-db-config
data:
  postgres_user: "postgres"
  postgres_password: "postgres"
  postgres_host: "participation-db-service"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: participation-db-deployment
  labels:
    app: participation-db
spec:
  serviceName: "participation-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: participation-db
  template:
    metadata:
      labels:
        app: participation-db
    spec:
      volumes:
      - name: participation-pv-storage
        persistentVolumeClaim:
          claimName: participation-pvc
      containers:
      - name: participation-db
        image: postgres:13.4
        resources:
          limits:
            memory: "125Mi"
            cpu: "125m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD 
          valueFrom:
            configMapKeyRef:
              name: participation-db-config
              key: postgres_password 
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: participation-pv-storage      
                
---
apiVersion: v1
kind: Service
metadata:
  name: participation-db-service
spec:
  selector:
    app: participation-db
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5432
      targetPort: 5432