apiVersion: apps/v1
kind: Deployment
metadata:
  name: participation-hutch-deployment
  labels:
    app: participation-hutch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participation-hutch
  template:
    metadata:
      labels:
        app: participation-hutch
    spec:
      containers:
      - name: participation-hutch
        image: slaac/participation-service:0.2.6
        command:
          - "hutch"
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: participation-db-config
              key: postgres_host
        - name: DATABASE_USER_NAME
          valueFrom:
            configMapKeyRef:
              name: participation-db-config
              key: postgres_user      
        - name: DATABASE_PASSWORD 
          valueFrom:
            configMapKeyRef:
              name: participation-db-config
              key: postgres_password
        - name: WEB_HOST 
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: web_host
        - name: RABBITMQ_USERNAME
          valueFrom:
           secretKeyRef:
            name: rabbitmq-cluster-default-user
            key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
           secretKeyRef:
            name: rabbitmq-cluster-default-user
            key: password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: rabbitmq_host
