apiVersion: v1
kind: PersistentVolume
metadata:
  name: event-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-db-config
data:
  postgres_user: "postgres"
  postgres_password: "postgres"
  postgres_host: "event-db-service"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: event-db-deployment
  labels:
    app: event-db
spec:
  serviceName: "event-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: event-db
  template:
    metadata:
      labels:
        app: event-db
    spec:
      volumes:
      - name: event-pv-storage
        persistentVolumeClaim:
          claimName: event-pvc
      containers:
      - name: event-db
        image: postgres:13.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD 
          valueFrom:
            configMapKeyRef:
              name: event-db-config
              key: postgres_password 
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: event-pv-storage      
                
---
apiVersion: v1
kind: Service
metadata:
  name: event-db-service
spec:
  selector:
    app: event-db
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5432
      targetPort: 5432