apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-deployment
  labels:
    app: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
      - name: event
        image: slaac/event-service:0.2.1
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: event-db-config
              key: postgres_host
        - name: DATABASE_USER_NAME
          valueFrom:
            configMapKeyRef:
              name: event-db-config
              key: postgres_user      
        - name: DATABASE_PASSWORD 
          valueFrom:
            configMapKeyRef:
              name: event-db-config
              key: postgres_password
        - name: WEB_HOST 
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: web_host  
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  selector:
    app: event
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
    